[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)]
  [ValidateNotNullOrEmpty()]
  [string]$SourceRoot,

  [ValidateNotNullOrEmpty()]
  [string]$OutputRoot = 'D:\tmp\warm-letter-ai-family\controlled-case-001',

  [switch]$SkipArchive,

  # A final handoff must include the reviewed long image generated by
  # create-case-001-long-image.ps1. The switch makes its absence a hard error.
  [switch]$RequireLongImage,

  # Useful when a browser is serving the current package. The artifacts are
  # read from this verified package while a new target directory is prepared.
  [string]$LongImageSourceRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$packageKind = 'warm-letter-controlled-demo'
$materialId = 'NUANJIAN-CASE-001'
$allowedOutputRoot = [System.IO.Path]::GetFullPath('D:\tmp').TrimEnd('\') + '\'
$utf8WithoutBom = [System.Text.UTF8Encoding]::new($false)
$requiredLongImageDisclosure = '队友固定审核稿 / 非实时 OpenAI / 由写信人确认'
$expectedDerivedPhotoSha256 = 'e09c8091a6676398d81ba40cd28d11c2f598e846748cfe2a069a09666ee6706b'
$expectedRecommendedDraftBodySha256 = '05c6479e695382252dbef55fd7c8fcba5da1cb7383101cc1fc8416913f942feb'
$expectedLongImage = [ordered]@{
  pngName = 'warm-letter-case-001-recommended-a.png'
  manifestName = 'warm-letter-case-001-recommended-a.manifest.json'
  bytes = 2183651L
  sha256 = '24b72c0626e12435e50bdcf911dac55914b092bcff147cfb61cf3d17b582f0ed'
  manifestSha256 = '281101bdd8aca3b90d865594ffa5b1e88ded9245fa94383df5ef9aa14f5baf8c'
  width = 1080
  height = 2631
}

$expectedSources = [ordered]@{
  photo = [ordered]@{
    relativePath = '素材\生活照片_商店货架.jpg'
    bytes = 1110199L
    sha256 = '885457751dbc4a9a0fe99fc0d7cfe1b5336c5b6e939beab0f4f1e07b138bf44d'
  }
  audio = [ordered]@{
    relativePath = '素材\语音_暖笺_1.m4a'
    bytes = 148876L
    sha256 = 'f9ec48c022bc98d9cc5ac3ff061c65108fe4827ccd8aac9ef1aca15ff88ea4dc'
  }
  draftText = [ordered]@{
    relativePath = '成品\三版温柔家书.txt'
    bytes = 1427L
    sha256 = '72092f4ea003c3aece40b529ef57b121c9300afd7f0315545e11efb37abf5df8'
  }
}

# These selected evidence files are safe to circulate inside the controlled team
# package. In particular, case_001.input.json and the generation prompt are not
# copied: the former can contain raw transcription fields and the latter is an
# implementation aid rather than evidence for a completed demonstration.
$expectedEvidenceSources = [ordered]@{
  caseOutput = [ordered]@{
    relativePath = '接口\case_001.output.json'
    outputPath = 'evidence/case-001-output.json'
    bytes = 2469L
    sha256 = 'd58fb7640e3d721efcd1ca396d97e8c81d531836f1eaf651120dc40d54e3f905'
  }
  safetyPolicy = [ordered]@{
    relativePath = '规则\content_safety_policy.json'
    outputPath = 'evidence/content-safety-policy.json'
    bytes = 1295L
    sha256 = '3e2ea2971e18b95e14e6001e969fab2285748ea664a6edb1c034dc0e21300171'
  }
  privacyReview = [ordered]@{
    relativePath = '核验\privacy_review.json'
    outputPath = 'evidence/privacy-review.json'
    bytes = 1095L
    sha256 = '9123abaca92d0d2be0355b182e94d75907177e17c0e490c3383fa08b6104e61d'
  }
  acceptanceTests = [ordered]@{
    relativePath = '核验\automated_acceptance_tests.json'
    outputPath = 'evidence/automated-acceptance-tests.json'
    bytes = 1104L
    sha256 = 'dd4553673a83e02cf08832fcbca511de908c46dd9491699f0d8bea875e94bffa'
  }
  materialManifest = [ordered]@{
    relativePath = '核验\material_manifest.csv'
    outputPath = 'evidence/material-manifest.csv'
    bytes = 384L
    sha256 = '124debfe43b1e348c9c3d6b330c745f2c3856482cb9d96ff2d8ba6ba9ac98a08'
  }
}

# The source hash pins the exact image. This rectangle retains the shelf, products,
# and price tag while ensuring pixels to the right of x=720 never enter the derivative.
$expectedPhotoWidth = 1080
$expectedPhotoHeight = 1919
$crop = [ordered]@{
  x = 0
  y = 420
  width = 720
  height = 1020
  jpegQuality = 92
}

function Get-LowerSha256 {
  param([Parameter(Mandatory = $true)][string]$LiteralPath)

  return (Get-FileHash -Algorithm SHA256 -LiteralPath $LiteralPath).Hash.ToLowerInvariant()
}

function Assert-ExpectedFile {
  param(
    [Parameter(Mandatory = $true)][string]$Root,
    [Parameter(Mandatory = $true)][System.Collections.IDictionary]$Expected,
    [Parameter(Mandatory = $true)][string]$Label
  )

  $path = Join-Path $Root $Expected.relativePath
  if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
    throw "$Label is missing at the expected relative path: $($Expected.relativePath)"
  }

  $item = Get-Item -LiteralPath $path
  if ($item.Length -ne $Expected.bytes) {
    throw "$Label size mismatch. Expected $($Expected.bytes) bytes; received $($item.Length)."
  }

  $hash = Get-LowerSha256 -LiteralPath $path
  if ($hash -ne $Expected.sha256) {
    throw "$Label SHA-256 mismatch. Refusing to build from unverified material."
  }

  return [pscustomobject]@{
    path = $path
    bytes = $item.Length
    sha256 = $hash
  }
}

function Test-SourceRootLayout {
  param([Parameter(Mandatory = $true)][string]$Root)

  return (
    (Test-Path -LiteralPath (Join-Path $Root '素材') -PathType Container) -and
    (Test-Path -LiteralPath (Join-Path $Root '成品') -PathType Container) -and
    (Test-Path -LiteralPath (Join-Path $Root '接口') -PathType Container) -and
    (Test-Path -LiteralPath (Join-Path $Root '核验') -PathType Container)
  )
}

function Resolve-SourceRootLayout {
  param([Parameter(Mandatory = $true)][string]$Root)

  if (Test-SourceRootLayout -Root $Root) {
    return $Root
  }

  $candidates = @(
    Get-ChildItem -LiteralPath $Root -Directory -Force | Where-Object {
      Test-SourceRootLayout -Root $_.FullName
    }
  )
  if ($candidates.Count -eq 1) {
    Write-Host "SourceRoot contains one wrapper directory; using its inner成果包目录。"
    return $candidates[0].FullName
  }
  if ($candidates.Count -gt 1) {
    throw 'SourceRoot contains multiple candidate成果包目录。请显式传入包含素材、成品、接口和核验的内层目录。'
  }

  throw 'SourceRoot must contain 素材、成品、接口和核验, or one uniquely identifiable inner成果包 directory.'
}

function Write-Utf8File {
  param(
    [Parameter(Mandatory = $true)][string]$LiteralPath,
    [Parameter(Mandatory = $true)][string]$Content
  )

  [System.IO.File]::WriteAllText($LiteralPath, $Content, $utf8WithoutBom)
}

function Assert-RelativeMediaUrl {
  param(
    [Parameter(Mandatory = $true)][string]$Value,
    [Parameter(Mandatory = $true)][string]$Label
  )

  if (
    -not $Value.StartsWith('./', [System.StringComparison]::Ordinal) -or
    $Value.Contains('\') -or
    $Value.Contains(':') -or
    $Value.Split('/') -contains '..'
  ) {
    throw "$Label must be a local POSIX-style relative URL: $Value"
  }
}

function Assert-GeneratedTextSafety {
  param([Parameter(Mandatory = $true)][string]$Root)

  $patterns = [ordered]@{
    'drive-qualified absolute path' = '(?i)\b[a-z]:[\\/]'
    'raw ASR field or label' = '(?i)raw[ _-]?asr'
    'API credential label' = '(?i)api[ _-]?key'
    'authorization bearer value' = '(?i)authorization\s*[:=]|bearer\s+[a-z0-9._-]+'
    'OpenAI-style secret token' = '(?i)\bsk-[a-z0-9_-]{8,}'
  }

  $textExtensions = @('.html', '.js', '.json', '.md', '.txt', '.csv')
  $textFiles = Get-ChildItem -LiteralPath $Root -Recurse -File | Where-Object {
    $_.Extension.ToLowerInvariant() -in $textExtensions
  }

  foreach ($file in $textFiles) {
    $content = [System.IO.File]::ReadAllText($file.FullName)
    foreach ($entry in $patterns.GetEnumerator()) {
      if ($content -match $entry.Value) {
        $relativePath = $file.FullName.Substring($Root.TrimEnd('\').Length).TrimStart('\')
        throw "Generated text safety check failed ($($entry.Key)) in $relativePath."
      }
    }
  }
}

function Assert-ControlledArchive {
  param(
    [Parameter(Mandatory = $true)][string]$ArchivePath,
    [Parameter(Mandatory = $true)][string[]]$RequiredEntries
  )

  Add-Type -AssemblyName System.IO.Compression
  Add-Type -AssemblyName System.IO.Compression.FileSystem
  $zip = [System.IO.Compression.ZipFile]::OpenRead($ArchivePath)
  try {
    $entryNames = @()
    foreach ($entry in $zip.Entries) {
      $rawName = [string]$entry.FullName
      $normalizedName = $rawName.Replace('\', '/')
      if (
        [string]::IsNullOrWhiteSpace($normalizedName) -or
        $rawName.Contains('\') -or
        $normalizedName.StartsWith('/') -or
        $normalizedName.Contains(':') -or
        ($normalizedName.Trim('/').Split('/') -contains '..')
      ) {
        throw "ZIP contains an unsafe entry path: $rawName"
      }
      $entryNames += $normalizedName
    }

    $duplicateEntries = @($entryNames | Group-Object { $_.ToLowerInvariant() } | Where-Object { $_.Count -gt 1 })
    if ($duplicateEntries.Count -gt 0) {
      throw "ZIP contains duplicate entry names: $($duplicateEntries[0].Name)"
    }

    $missingEntries = @($RequiredEntries | Where-Object { $_ -notin $entryNames })
    if ($missingEntries.Count -gt 0) {
      throw "ZIP structure check failed. Missing: $($missingEntries -join ', ')"
    }

    $manifestEntry = $zip.Entries | Where-Object {
      $_.FullName.Replace('\', '/') -eq 'manifest.json'
    } | Select-Object -First 1
    if ($null -eq $manifestEntry) {
      throw 'ZIP does not contain a root manifest.json.'
    }

    $manifestStream = $manifestEntry.Open()
    $manifestBytes = [System.IO.MemoryStream]::new()
    try {
      $manifestStream.CopyTo($manifestBytes)
      $manifestText = [System.Text.Encoding]::UTF8.GetString($manifestBytes.ToArray())
    } finally {
      $manifestStream.Dispose()
      $manifestBytes.Dispose()
    }

    try {
      $archiveManifest = $manifestText | ConvertFrom-Json
    } catch {
      throw 'ZIP root manifest.json is not valid UTF-8 JSON.'
    }
    if ($archiveManifest.packageKind -ne $packageKind -or $archiveManifest.materialId -ne $materialId) {
      throw 'ZIP manifest does not identify the controlled CASE-001 package.'
    }

    return [pscustomobject]@{
      entryCount = $entryNames.Count
      entries = @($entryNames)
    }
  } finally {
    $zip.Dispose()
  }
}

function New-ControlledArchive {
  param(
    [Parameter(Mandatory = $true)][string]$SourceDirectory,
    [Parameter(Mandatory = $true)][string]$ArchivePath
  )

  Add-Type -AssemblyName System.IO.Compression
  Add-Type -AssemblyName System.IO.Compression.FileSystem
  if (Test-Path -LiteralPath $ArchivePath) {
    throw "Archive staging path already exists: $ArchivePath"
  }

  $sourceFull = [System.IO.Path]::GetFullPath($SourceDirectory).TrimEnd('\')
  $sourcePrefix = $sourceFull + '\'
  $entryTimestamp = [System.DateTimeOffset]::Parse('2026-08-28T00:00:00Z')
  $zip = [System.IO.Compression.ZipFile]::Open(
    $ArchivePath,
    [System.IO.Compression.ZipArchiveMode]::Create
  )
  try {
    $sourceFiles = @(Get-ChildItem -LiteralPath $sourceFull -Recurse -File | Sort-Object FullName)
    foreach ($sourceFile in $sourceFiles) {
      if (-not $sourceFile.FullName.StartsWith($sourcePrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Archive source escaped its staging directory: $($sourceFile.FullName)"
      }

      $entryName = $sourceFile.FullName.Substring($sourcePrefix.Length).Replace('\', '/')
      if (
        [string]::IsNullOrWhiteSpace($entryName) -or
        $entryName.StartsWith('/') -or
        $entryName.Contains(':') -or
        ($entryName.Split('/') -contains '..')
      ) {
        throw "Refusing to create an unsafe ZIP entry path: $entryName"
      }

      $entry = $zip.CreateEntry($entryName, [System.IO.Compression.CompressionLevel]::Optimal)
      $entry.LastWriteTime = $entryTimestamp
      $sourceStream = [System.IO.File]::OpenRead($sourceFile.FullName)
      $entryStream = $entry.Open()
      try {
        $sourceStream.CopyTo($entryStream)
      } finally {
        $entryStream.Dispose()
        $sourceStream.Dispose()
      }
    }
  } finally {
    $zip.Dispose()
  }
}

function New-CroppedPhoto {
  param(
    [Parameter(Mandatory = $true)][string]$SourcePath,
    [Parameter(Mandatory = $true)][string]$DestinationPath
  )

  Add-Type -AssemblyName System.Drawing

  $sourceImage = [System.Drawing.Image]::FromFile($SourcePath)
  try {
    if ($sourceImage.Width -ne $expectedPhotoWidth -or $sourceImage.Height -ne $expectedPhotoHeight) {
      throw "Photo dimensions mismatch. Expected ${expectedPhotoWidth}x${expectedPhotoHeight}; received $($sourceImage.Width)x$($sourceImage.Height)."
    }

    if (
      $crop.x -lt 0 -or
      $crop.y -lt 0 -or
      ($crop.x + $crop.width) -gt $sourceImage.Width -or
      ($crop.y + $crop.height) -gt $sourceImage.Height
    ) {
      throw 'Configured crop rectangle falls outside the verified source image.'
    }

    $croppedImage = [System.Drawing.Bitmap]::new(
      $crop.width,
      $crop.height,
      [System.Drawing.Imaging.PixelFormat]::Format24bppRgb
    )
    try {
      if ($sourceImage.HorizontalResolution -gt 0 -and $sourceImage.VerticalResolution -gt 0) {
        $croppedImage.SetResolution($sourceImage.HorizontalResolution, $sourceImage.VerticalResolution)
      }

      $graphics = [System.Drawing.Graphics]::FromImage($croppedImage)
      try {
        $graphics.CompositingMode = [System.Drawing.Drawing2D.CompositingMode]::SourceCopy
        $graphics.CompositingQuality = [System.Drawing.Drawing2D.CompositingQuality]::HighQuality
        $graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $graphics.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality

        $destinationRectangle = [System.Drawing.Rectangle]::new(0, 0, $crop.width, $crop.height)
        $sourceRectangle = [System.Drawing.Rectangle]::new($crop.x, $crop.y, $crop.width, $crop.height)
        $graphics.DrawImage(
          $sourceImage,
          $destinationRectangle,
          $sourceRectangle,
          [System.Drawing.GraphicsUnit]::Pixel
        )
      } finally {
        $graphics.Dispose()
      }

      $jpegCodec = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() |
        Where-Object { $_.MimeType -eq 'image/jpeg' } |
        Select-Object -First 1
      if ($null -eq $jpegCodec) {
        throw 'No JPEG encoder is available through System.Drawing.'
      }

      $encoderParameters = [System.Drawing.Imaging.EncoderParameters]::new(1)
      try {
        $encoderParameters.Param[0] = [System.Drawing.Imaging.EncoderParameter]::new(
          [System.Drawing.Imaging.Encoder]::Quality,
          [long]$crop.jpegQuality
        )
        $croppedImage.Save($DestinationPath, $jpegCodec, $encoderParameters)
      } finally {
        if ($null -ne $encoderParameters.Param[0]) {
          $encoderParameters.Param[0].Dispose()
        }
        $encoderParameters.Dispose()
      }
    } finally {
      $croppedImage.Dispose()
    }
  } finally {
    $sourceImage.Dispose()
  }

  $verificationImage = [System.Drawing.Image]::FromFile($DestinationPath)
  try {
    if ($verificationImage.Width -ne $crop.width -or $verificationImage.Height -ne $crop.height) {
      throw "Cropped photo verification failed. Expected $($crop.width)x$($crop.height); received $($verificationImage.Width)x$($verificationImage.Height)."
    }
  } finally {
    $verificationImage.Dispose()
  }
}

function Assert-RecognizedPackageRoot {
  param(
    [Parameter(Mandatory = $true)][string]$Root,
    [switch]$Required
  )

  if (-not (Test-Path -LiteralPath $Root)) {
    if ($Required) {
      throw "Required controlled package directory is missing: $Root"
    }
    return $false
  }
  if (-not (Test-Path -LiteralPath $Root -PathType Container)) {
    throw 'OutputRoot exists but is not a directory.'
  }

  $existingManifestPath = Join-Path $Root 'manifest.json'
  if (-not (Test-Path -LiteralPath $existingManifestPath -PathType Leaf)) {
    throw 'Refusing to replace an existing directory without a recognized manifest.'
  }

  try {
    $existingManifest = Get-Content -LiteralPath $existingManifestPath -Raw -Encoding UTF8 | ConvertFrom-Json
  } catch {
    throw 'Refusing to replace an existing directory with an invalid manifest.'
  }
  if ($existingManifest.packageKind -ne $packageKind -or $existingManifest.materialId -ne $materialId) {
    throw 'Refusing to replace an existing directory owned by another package.'
  }

  return $true
}

function Assert-ExistingLongImage {
  param([Parameter(Mandatory = $true)][string]$Root)

  $exportsRoot = Join-Path $Root 'exports'
  if (-not (Test-Path -LiteralPath $exportsRoot -PathType Container)) {
    throw 'The final handoff requires exports/ from create-case-001-long-image.ps1, but it is missing.'
  }

  $exportFiles = @(Get-ChildItem -LiteralPath $exportsRoot -Recurse -File | Sort-Object FullName)
  $actualNames = @($exportFiles | ForEach-Object {
    $_.FullName.Substring($exportsRoot.TrimEnd('\').Length).TrimStart('\').Replace('\', '/')
  })
  $expectedNames = @($expectedLongImage.pngName, $expectedLongImage.manifestName)
  if ($actualNames.Count -ne $expectedNames.Count -or @($actualNames | Where-Object { $_ -notin $expectedNames }).Count -gt 0) {
    throw 'exports/ must contain exactly the reviewed CASE-001 PNG and its verification manifest.'
  }

  $pngPath = Join-Path $exportsRoot $expectedLongImage.pngName
  $longImageManifestPath = Join-Path $exportsRoot $expectedLongImage.manifestName
  foreach ($requiredPath in @($pngPath, $longImageManifestPath)) {
    if (-not (Test-Path -LiteralPath $requiredPath -PathType Leaf)) {
      throw "Required reviewed long-image artifact is missing: $([System.IO.Path]::GetFileName($requiredPath))"
    }
  }

  $pngItem = Get-Item -LiteralPath $pngPath
  if ($pngItem.Length -ne $expectedLongImage.bytes -or (Get-LowerSha256 -LiteralPath $pngPath) -ne $expectedLongImage.sha256) {
    throw 'The reviewed long image does not match its pinned CASE-001 bytes or SHA-256.'
  }
  if ((Get-LowerSha256 -LiteralPath $longImageManifestPath) -ne $expectedLongImage.manifestSha256) {
    throw 'The reviewed long-image verification manifest does not match its pinned SHA-256.'
  }

  try {
    $longImageManifest = Get-Content -LiteralPath $longImageManifestPath -Raw -Encoding UTF8 | ConvertFrom-Json
  } catch {
    throw "Long-image verification manifest is invalid JSON: $($_.Exception.Message)"
  }
  if (
    $longImageManifest.schemaVersion -ne 1 -or
    $longImageManifest.packageKind -ne 'warm-letter-case-001-long-image' -or
    $longImageManifest.caseId -ne $materialId -or
    $longImageManifest.recommendedDraftId -ne 'A' -or
    $longImageManifest.draftName -ne 'A｜短笺版（主推荐）' -or
    $longImageManifest.draftBodySha256 -ne $expectedRecommendedDraftBodySha256 -or
    $longImageManifest.disclosure -ne $requiredLongImageDisclosure -or
    $longImageManifest.sourcePhoto.sha256 -ne $expectedDerivedPhotoSha256 -or
    [int]$longImageManifest.sourcePhoto.width -ne $crop.width -or
    [int]$longImageManifest.sourcePhoto.height -ne $crop.height -or
    $longImageManifest.output.fileName -ne $expectedLongImage.pngName -or
    $longImageManifest.output.mediaType -ne 'image/png' -or
    [long]$longImageManifest.output.bytes -ne $expectedLongImage.bytes -or
    $longImageManifest.output.sha256 -ne $expectedLongImage.sha256 -or
    [int]$longImageManifest.output.width -ne $expectedLongImage.width -or
    [int]$longImageManifest.output.height -ne $expectedLongImage.height -or
    -not [bool]$longImageManifest.bodyStructure.greetingIncluded -or
    -not [bool]$longImageManifest.bodyStructure.signatureIncluded -or
    [int]$longImageManifest.bodyStructure.paragraphCount -lt 1 -or
    -not [bool]$longImageManifest.controls.bodyReadFromRecommendedDraft -or
    -not [bool]$longImageManifest.controls.physicalCropUsedWithoutAdditionalCropping -or
    -not [bool]$longImageManifest.controls.sourceFilesUnchanged -or
    [bool]$longImageManifest.controls.absolutePathsIncluded -or
    [bool]$longImageManifest.controls.credentialsIncluded
  ) {
    throw 'Long-image verification manifest does not describe the reviewed CASE-001 recommendation and controls.'
  }

  Add-Type -AssemblyName System.Drawing
  $image = [System.Drawing.Image]::FromFile($pngPath)
  try {
    if ($image.Width -ne $expectedLongImage.width -or $image.Height -ne $expectedLongImage.height) {
      throw "Long image dimensions mismatch. Expected $($expectedLongImage.width)x$($expectedLongImage.height); received $($image.Width)x$($image.Height)."
    }
  } finally {
    $image.Dispose()
  }

  return [pscustomobject]@{
    exportsRoot = $exportsRoot
    pngPath = $pngPath
    manifestPath = $longImageManifestPath
    bytes = $pngItem.Length
    sha256 = $expectedLongImage.sha256
    manifestSha256 = $expectedLongImage.manifestSha256
  }
}

$sourceRootFull = [System.IO.Path]::GetFullPath($SourceRoot).TrimEnd('\')
$outputRootFull = [System.IO.Path]::GetFullPath($OutputRoot).TrimEnd('\')

if (-not (Test-Path -LiteralPath $sourceRootFull -PathType Container)) {
  throw "SourceRoot is not an existing directory: $sourceRootFull"
}
$sourceRootFull = Resolve-SourceRootLayout -Root $sourceRootFull

if (-not $outputRootFull.StartsWith($allowedOutputRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
  throw "OutputRoot must be a child directory of $($allowedOutputRoot.TrimEnd('\'))."
}

$outputLeaf = [System.IO.Path]::GetFileName($outputRootFull)
if ([string]::IsNullOrWhiteSpace($outputLeaf)) {
  throw 'OutputRoot must name a package directory, not a drive or temp root.'
}

$existingPackagePresent = Assert-RecognizedPackageRoot -Root $outputRootFull
$existingLongImage = $null
if (-not [string]::IsNullOrWhiteSpace($LongImageSourceRoot)) {
  $longImageSourceRootFull = [System.IO.Path]::GetFullPath($LongImageSourceRoot).TrimEnd('\')
  if (-not $longImageSourceRootFull.StartsWith($allowedOutputRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "LongImageSourceRoot must be a child directory of $($allowedOutputRoot.TrimEnd('\'))."
  }
  [void](Assert-RecognizedPackageRoot -Root $longImageSourceRootFull -Required)
  $existingExportsRoot = Join-Path $longImageSourceRootFull 'exports'
  if (Test-Path -LiteralPath $existingExportsRoot -PathType Container) {
    $existingLongImage = Assert-ExistingLongImage -Root $longImageSourceRootFull
  } elseif ($RequireLongImage) {
    throw 'RequireLongImage was specified, but LongImageSourceRoot has no exports/ directory.'
  }
} elseif ($existingPackagePresent) {
  $existingExportsRoot = Join-Path $outputRootFull 'exports'
  if (Test-Path -LiteralPath $existingExportsRoot -PathType Container) {
    # Preserve a reviewed export by default. This avoids silently dropping the
    # shareable long image when someone refreshes the package for a new handoff.
    $existingLongImage = Assert-ExistingLongImage -Root $outputRootFull
  } elseif ($RequireLongImage) {
    throw 'RequireLongImage was specified, but the current controlled package has no exports/ directory.'
  }
} elseif ($RequireLongImage) {
  throw 'RequireLongImage was specified, but there is no prior controlled package from which to preserve the reviewed export.'
}

$photoSource = Assert-ExpectedFile -Root $sourceRootFull -Expected $expectedSources.photo -Label 'Photo'
$audioSource = Assert-ExpectedFile -Root $sourceRootFull -Expected $expectedSources.audio -Label 'Audio'
$draftTextSource = Assert-ExpectedFile -Root $sourceRootFull -Expected $expectedSources.draftText -Label 'Draft text'

$evidenceSources = [ordered]@{}
foreach ($evidenceEntry in $expectedEvidenceSources.GetEnumerator()) {
  $evidenceSources[$evidenceEntry.Key] = Assert-ExpectedFile -Root $sourceRootFull -Expected $evidenceEntry.Value -Label "Evidence $($evidenceEntry.Key)"
}

$caseOutputPath = Join-Path $sourceRootFull '接口\case_001.output.json'
$acceptanceTestsPath = Join-Path $sourceRootFull '核验\automated_acceptance_tests.json'
foreach ($requiredStructuredFile in @($caseOutputPath, $acceptanceTestsPath)) {
  if (-not (Test-Path -LiteralPath $requiredStructuredFile -PathType Leaf)) {
    throw "Required structured source file is missing: $([System.IO.Path]::GetFileName($requiredStructuredFile))"
  }
}

try {
  $caseOutput = Get-Content -LiteralPath $caseOutputPath -Raw -Encoding UTF8 | ConvertFrom-Json
  $parsedAcceptanceTests = Get-Content -LiteralPath $acceptanceTestsPath -Raw -Encoding UTF8 | ConvertFrom-Json
  $acceptanceTests = @()
  foreach ($acceptanceTest in $parsedAcceptanceTests) {
    $acceptanceTests += $acceptanceTest
  }
  $safetyPolicy = Get-Content -LiteralPath $evidenceSources.safetyPolicy.path -Raw -Encoding UTF8 | ConvertFrom-Json
  $privacyReview = Get-Content -LiteralPath $evidenceSources.privacyReview.path -Raw -Encoding UTF8 | ConvertFrom-Json
} catch {
  throw "Structured source JSON is invalid: $($_.Exception.Message)"
}

if ($safetyPolicy.version -ne '1.0' -or [string]::IsNullOrWhiteSpace([string]$safetyPolicy.default_behavior)) {
  throw 'Content safety policy is not the expected reviewed version.'
}
if ($privacyReview.material_id -ne $materialId -or [string]::IsNullOrWhiteSpace([string]$privacyReview.release_decision)) {
  throw 'Privacy review is not a release decision for the controlled CASE-001 material.'
}
$materialManifestText = [System.IO.File]::ReadAllText($evidenceSources.materialManifest.path)
if (
  -not $materialManifestText.Contains($photoSource.sha256) -or
  -not $materialManifestText.Contains($audioSource.sha256)
) {
  throw 'The teammate material manifest does not identify both pinned source media files.'
}

$expectedDraftNames = @(
  'A｜短笺版（主推荐）',
  'B｜日常版（信息更完整）',
  'C｜留白版（更克制）'
)
$sourceLetters = @($caseOutput.letters)
if ($caseOutput.material_id -ne $materialId) {
  throw "Unexpected material_id in case_001.output.json: $($caseOutput.material_id)"
}
if ($sourceLetters.Count -ne 3) {
  throw "Expected exactly three reviewed drafts; received $($sourceLetters.Count)."
}
if ($caseOutput.recommended_version -ne $expectedDraftNames[0]) {
  throw 'The reviewed output no longer recommends draft A. Manual reconciliation is required.'
}

$reviewedDraftText = ([System.IO.File]::ReadAllText($draftTextSource.path) -replace "`r`n", "`n")
for ($index = 0; $index -lt $sourceLetters.Count; $index += 1) {
  $letter = $sourceLetters[$index]
  if ($letter.name -ne $expectedDraftNames[$index]) {
    throw "Draft name mismatch at position $($index + 1)."
  }
  if ([string]::IsNullOrWhiteSpace([string]$letter.body)) {
    throw "Draft $($index + 1) has an empty body."
  }

  $normalizedBody = ([string]$letter.body -replace "`r`n", "`n")
  if (-not $reviewedDraftText.Contains($normalizedBody)) {
    throw "Draft $($index + 1) does not match the hash-verified review text."
  }
}

if ($caseOutput.safety.status -ne 'PASS' -or [bool]$caseOutput.safety.manual_review_required) {
  throw 'The reviewed output is not in the expected PASS / no-manual-review state.'
}

$expectedTestIds = 1..7 | ForEach-Object { 'T{0:D2}' -f $_ }
if ($acceptanceTests.Count -ne $expectedTestIds.Count) {
  throw "Expected seven acceptance tests; received $($acceptanceTests.Count)."
}
for ($index = 0; $index -lt $expectedTestIds.Count; $index += 1) {
  if ($acceptanceTests[$index].id -ne $expectedTestIds[$index] -or $acceptanceTests[$index].result -ne 'PASS') {
    throw "Acceptance test $($expectedTestIds[$index]) is missing, reordered, or not PASS."
  }
}

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$demoPageSource = Join-Path $repositoryRoot 'docs\product-demo\index.html'
if (-not (Test-Path -LiteralPath $demoPageSource -PathType Leaf)) {
  throw 'Repository demo page is missing: docs/product-demo/index.html'
}

$photoUrl = './media/case-001-photo-crop.jpg'
$audioUrl = './media/case-001-audio.m4a'
Assert-RelativeMediaUrl -Value $photoUrl -Label 'photoUrl'
Assert-RelativeMediaUrl -Value $audioUrl -Label 'audioUrl'

$outputParent = Split-Path -Parent $outputRootFull
New-Item -ItemType Directory -Force -Path $outputParent | Out-Null

$operationId = [System.Guid]::NewGuid().ToString('N')
$stage = Join-Path $outputParent ".$outputLeaf.staging-$operationId"
$backup = Join-Path $outputParent ".$outputLeaf.backup-$operationId"
$archivePath = "$outputRootFull.zip"
$archiveStage = Join-Path $outputParent ".$outputLeaf.staging-$operationId.zip"
$archiveBackup = Join-Path $outputParent ".$outputLeaf.backup-$operationId.zip"
$requiredArchiveEntries = @(
  'index.html',
  'demo-case.js',
  'demo-case.json',
  'manifest.json',
  'README.md',
  'PROJECT_INTEGRATION.md',
  'media/case-001-photo-crop.jpg',
  'media/case-001-audio.m4a'
)
foreach ($evidenceEntry in $expectedEvidenceSources.GetEnumerator()) {
  $requiredArchiveEntries += [string]$evidenceEntry.Value.outputPath
}
if ($null -ne $existingLongImage) {
  $requiredArchiveEntries += "exports/$($expectedLongImage.pngName)"
  $requiredArchiveEntries += "exports/$($expectedLongImage.manifestName)"
}
$minimumExistingArchiveEntries = @(
  'index.html',
  'demo-case.js',
  'manifest.json',
  'media/case-001-photo-crop.jpg',
  'media/case-001-audio.m4a'
)
$stageExists = $false
$backupExists = $false
$archiveStageExists = $false
$archiveBackupExists = $false
$newOutputInstalled = $false
$newArchiveInstalled = $false

try {
  New-Item -ItemType Directory -Path $stage | Out-Null
  $stageExists = $true
  New-Item -ItemType Directory -Path (Join-Path $stage 'media') | Out-Null
  New-Item -ItemType Directory -Path (Join-Path $stage 'evidence') | Out-Null

  $photoOutput = Join-Path $stage 'media\case-001-photo-crop.jpg'
  $audioOutput = Join-Path $stage 'media\case-001-audio.m4a'
  New-CroppedPhoto -SourcePath $photoSource.path -DestinationPath $photoOutput
  Copy-Item -LiteralPath $audioSource.path -Destination $audioOutput
  Copy-Item -LiteralPath $demoPageSource -Destination (Join-Path $stage 'index.html')

  $derivedPhotoHash = Get-LowerSha256 -LiteralPath $photoOutput
  $copiedAudioHash = Get-LowerSha256 -LiteralPath $audioOutput
  if ($derivedPhotoHash -eq $photoSource.sha256) {
    throw 'Photo crop unexpectedly matches the source hash; the original photo may have been copied.'
  }
  if ($derivedPhotoHash -ne $expectedDerivedPhotoSha256) {
    throw 'Physical photo crop does not match the pinned CASE-001 privacy-safe derivative.'
  }
  if ($copiedAudioHash -ne $audioSource.sha256) {
    throw 'Copied audio failed its SHA-256 verification.'
  }

  $evidenceOutputs = [ordered]@{}
  foreach ($evidenceEntry in $expectedEvidenceSources.GetEnumerator()) {
    $source = $evidenceSources[$evidenceEntry.Key]
    $relativeOutputPath = [string]$evidenceEntry.Value.outputPath
    $destinationPath = Join-Path $stage $relativeOutputPath.Replace('/', '\')
    Copy-Item -LiteralPath $source.path -Destination $destinationPath
    $copiedEvidence = Get-Item -LiteralPath $destinationPath
    $copiedEvidenceHash = Get-LowerSha256 -LiteralPath $destinationPath
    if ($copiedEvidence.Length -ne $source.bytes -or $copiedEvidenceHash -ne $source.sha256) {
      throw "Copied evidence $($evidenceEntry.Key) failed its size or SHA-256 verification."
    }
    $evidenceOutputs[$evidenceEntry.Key] = [ordered]@{
      path = $relativeOutputPath
      sourceRelativePath = ([string]$evidenceEntry.Value.relativePath).Replace('\', '/')
      bytes = $copiedEvidence.Length
      sha256 = $copiedEvidenceHash
    }
  }

  $longImageOutput = $null
  if ($null -ne $existingLongImage) {
    $stageExportsRoot = Join-Path $stage 'exports'
    New-Item -ItemType Directory -Path $stageExportsRoot | Out-Null
    $longImageOutputPath = Join-Path $stageExportsRoot $expectedLongImage.pngName
    $longImageManifestOutputPath = Join-Path $stageExportsRoot $expectedLongImage.manifestName
    Copy-Item -LiteralPath $existingLongImage.pngPath -Destination $longImageOutputPath
    Copy-Item -LiteralPath $existingLongImage.manifestPath -Destination $longImageManifestOutputPath
    if (
      (Get-LowerSha256 -LiteralPath $longImageOutputPath) -ne $existingLongImage.sha256 -or
      (Get-LowerSha256 -LiteralPath $longImageManifestOutputPath) -ne $existingLongImage.manifestSha256
    ) {
      throw 'Copied long-image export failed its SHA-256 verification.'
    }
    $longImageOutput = [ordered]@{
      png = [ordered]@{
        path = "exports/$($expectedLongImage.pngName)"
        bytes = $existingLongImage.bytes
        sha256 = $existingLongImage.sha256
        width = $expectedLongImage.width
        height = $expectedLongImage.height
      }
      verificationManifest = [ordered]@{
        path = "exports/$($expectedLongImage.manifestName)"
        sha256 = $existingLongImage.manifestSha256
      }
    }
  }

  # These are reviewed CASE-001 links, not browser-side keyword guesses. They
  # preserve the team member's evidence map while making each rendered paragraph
  # traceable to the physically included voice or privacy-safe photo derivative.
  $reviewedEvidenceDefinitions = @(
    [ordered]@{ id = 'evidence-01'; sourceRefs = @('voice') },
    [ordered]@{ id = 'evidence-02'; sourceRefs = @('voice') },
    [ordered]@{ id = 'evidence-03'; sourceRefs = @('voice') },
    [ordered]@{ id = 'evidence-04'; sourceRefs = @('photo') }
  )
  $evidenceMap = @(
    for ($index = 0; $index -lt $caseOutput.evidence_map.Count; $index += 1) {
      $source = [string]$caseOutput.evidence_map[$index].source
      [ordered]@{
        id = [string]$reviewedEvidenceDefinitions[$index].id
        fact = [string]$caseOutput.evidence_map[$index].output_fact
        # Keep both spellings while consumers transition to sourceLabel.
        source = $source
        sourceLabel = $source
        sourceRefs = @($reviewedEvidenceDefinitions[$index].sourceRefs)
        confidence = [string]$caseOutput.evidence_map[$index].confidence
      }
    }
  )
  if ($evidenceMap.Count -ne 4) {
    throw "Expected four reviewed evidence mappings; received $($evidenceMap.Count)."
  }

  $reviewedParagraphEvidence = [ordered]@{
    A = @(
      [ordered]@{ evidenceIds = @('evidence-01', 'evidence-02', 'evidence-03', 'evidence-04'); sourceRefs = @('voice', 'photo') }
    )
    B = @(
      [ordered]@{ evidenceIds = @('evidence-01', 'evidence-02', 'evidence-03', 'evidence-04'); sourceRefs = @('voice', 'photo') },
      [ordered]@{ evidenceIds = @('evidence-02', 'evidence-03'); sourceRefs = @('voice') }
    )
    C = @(
      [ordered]@{ evidenceIds = @('evidence-01', 'evidence-02', 'evidence-03', 'evidence-04'); sourceRefs = @('voice', 'photo') },
      [ordered]@{ evidenceIds = @('evidence-02', 'evidence-03'); sourceRefs = @('voice') }
    )
  }
  $evidenceById = @{}
  foreach ($evidence in $evidenceMap) {
    $evidenceById[[string]$evidence.id] = $evidence
  }

  $draftMetadata = @(
    [ordered]@{ id = 'A'; label = '短笺版' },
    [ordered]@{ id = 'B'; label = '日常版' },
    [ordered]@{ id = 'C'; label = '留白版' }
  )
  $drafts = for ($index = 0; $index -lt $sourceLetters.Count; $index += 1) {
    $draftId = [string]$draftMetadata[$index].id
    $paragraphEvidence = @($reviewedParagraphEvidence[$draftId])
    $blocks = @(
      [regex]::Split(([string]$sourceLetters[$index].body).Trim(), '\r?\n\s*\r?\n') |
        ForEach-Object { $_.Trim() } |
        Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
    )
    if ($blocks.Count -lt 3) {
      throw "Reviewed draft $draftId must contain a greeting, at least one body paragraph, and a signature."
    }
    if ($paragraphEvidence.Count -ne ($blocks.Count - 2)) {
      throw "Reviewed paragraph evidence count mismatch for draft $draftId. Expected $($blocks.Count - 2); received $($paragraphEvidence.Count)."
    }

    $validatedParagraphEvidence = @(
      foreach ($entry in $paragraphEvidence) {
        $evidenceIds = @($entry.evidenceIds | ForEach-Object { [string]$_ })
        $sourceRefs = @($entry.sourceRefs | ForEach-Object { [string]$_ })
        if ($evidenceIds.Count -eq 0 -or $sourceRefs.Count -eq 0) {
          throw "Reviewed paragraph evidence for draft $draftId cannot be empty."
        }
        foreach ($evidenceId in $evidenceIds) {
          if (-not $evidenceById.ContainsKey($evidenceId)) {
            throw "Draft $draftId references an unknown reviewed evidence ID: $evidenceId"
          }
        }
        $derivedSourceRefs = @(
          $evidenceIds |
            ForEach-Object { @($evidenceById[$_].sourceRefs) } |
            Select-Object -Unique
        )
        $sourceRefDiff = @(Compare-Object -ReferenceObject $derivedSourceRefs -DifferenceObject $sourceRefs)
        if ($sourceRefDiff.Count -gt 0) {
          throw "Draft $draftId has sourceRefs that do not match its reviewed evidence IDs."
        }
        [ordered]@{
          evidenceIds = $evidenceIds
          sourceRefs = $sourceRefs
        }
      }
    )

    [ordered]@{
      id = $draftId
      name = [string]$sourceLetters[$index].name
      label = $draftMetadata[$index].label
      body = [string]$sourceLetters[$index].body
      paragraphEvidence = $validatedParagraphEvidence
    }
  }

  $safetyLabels = [ordered]@{
    T01 = '中性称呼'
    T02 = '不确定名词上位概括'
    T03 = '照片隐私裁切'
    T04 = '只写画面可见事实'
    T05 = '温柔克制语气'
    T06 = '不冒充未核实身份'
    T07 = '照片与语音离线可用'
  }
  $safetyTestResults = @($acceptanceTests | ForEach-Object {
    [ordered]@{
      id = [string]$_.id
      label = [string]$safetyLabels[[string]$_.id]
      criterion = [string]$_.expected
      status = [string]$_.result
    }
  })

  $demoCase = [ordered]@{
    schemaVersion = 1
    caseId = $materialId
    mode = 'controlled-team'
    provenanceLabel = '受控真实素材 / 固定审核稿 / 非实时 OpenAI 调用'
    disclosure = '本地团队包已装入队友提供的语音和隐私裁切照片。三版文字是固定审核稿，页面不调用实时 OpenAI。'
    materialId = $materialId
    title = '把普通的一天，轻轻寄回家'
    photoUrl = $photoUrl
    audioUrl = $audioUrl
    audioDurationSeconds = 8.895
    photoCrop = [ordered]@{
      sourceWidth = $expectedPhotoWidth
      sourceHeight = $expectedPhotoHeight
      x = $crop.x
      y = $crop.y
      width = $crop.width
      height = $crop.height
      jpegQuality = $crop.jpegQuality
      derivativeSha256 = $derivedPhotoHash
    }
    sourceHashes = [ordered]@{
      photoOriginal = $photoSource.sha256
      audioOriginal = $audioSource.sha256
      draftsOriginal = $draftTextSource.sha256
    }
    drafts = @($drafts)
    recommendedDraftId = 'A'
    evidenceMap = @($evidenceMap)
    safety = [ordered]@{
      status = [string]$caseOutput.safety.status
      manualReviewRequired = [bool]$caseOutput.safety.manual_review_required
      notes = @($caseOutput.safety.notes | ForEach-Object { [string]$_ })
    }
    safetyTests = @($expectedTestIds)
    safetyTestResults = @($safetyTestResults)
  }

  $demoCaseJson = $demoCase | ConvertTo-Json -Depth 12
  Write-Utf8File -LiteralPath (Join-Path $stage 'demo-case.json') -Content ($demoCaseJson + "`n")
  Write-Utf8File -LiteralPath (Join-Path $stage 'demo-case.js') -Content ("window.WARM_LETTER_DEMO_CASE = $demoCaseJson;`n")

  $readme = @'
# 暖笺受控真实素材演示

打开 `index.html` 即可查看。页面、照片、音频和配置均使用相对路径，整个目录可以移动到另一台电脑后继续离线演示。

`PROJECT_INTEGRATION.md` 是这份成果包的工作汇报入口：它区分队友提供的内容资产与本项目已经完成的产品接入，并标明每项相对入口和未完成边界。

## 展示口径

- 照片是队友提供原图的隐私裁切衍生图；原始照片不在本目录中。
- 语音是队友提供的示例原音，仅限团队授权范围内受控展示。
- A/B/C 三版文字来自固定审核稿，A 版为推荐稿。
- 本页不是实时 OpenAI 调用，也不代表微信双真机、真人测试或生产部署已完成。

## 相对路径

```text
./index.html
./PROJECT_INTEGRATION.md
./demo-case.js
./demo-case.json
./manifest.json
./evidence/case-001-output.json
./evidence/content-safety-policy.json
./evidence/privacy-review.json
./evidence/automated-acceptance-tests.json
./evidence/material-manifest.csv
./media/case-001-photo-crop.jpg
./media/case-001-audio.m4a
./exports/warm-letter-case-001-recommended-a.png
./exports/warm-letter-case-001-recommended-a.manifest.json
```

不要把本目录上传到公开仓库或公开网盘。对外发送前，应再次确认照片和语音的授权范围。
'@
  Write-Utf8File -LiteralPath (Join-Path $stage 'README.md') -Content ($readme.TrimStart() + "`n")

  $projectIntegration = @'
# 暖笺 CASE-001 项目接入说明

## 这份包展示什么

这是一份团队内部的受控成果包：它把队友已经审核的真实素材和内容成果，接入本项目的互动演示、隐私控制、可追溯证据和可转发的长图呈现。页面使用固定审核稿，不执行实时 OpenAI 调用。

## 队友提供的内容成果

| 队友源材料相对路径 | 本包相对入口 | 使用方式 |
| --- | --- | --- |
| `素材/语音_暖笺_1.m4a` | `./media/case-001-audio.m4a` | 原始 m4a，仅用于团队内部播放；正文只采用已经审核的安全语义。 |
| `素材/生活照片_商店货架.jpg` | `./media/case-001-photo-crop.jpg` | 物理裁切派生图，只保留货架、商品与价签；原始照片不在包内。 |
| `成品/三版温柔家书.txt` | `./demo-case.json` | 队友固定审核稿，A 为主推荐版本。 |
| `接口/case_001.output.json` | `./evidence/case-001-output.json` | 三版正文、证据映射与安全结论。 |
| `规则/content_safety_policy.json` | `./evidence/content-safety-policy.json` | 身份、事实、语气和不确定信息的边界。 |
| `核验/privacy_review.json` | `./evidence/privacy-review.json` | 说明路人不识别、不描述，公开时继续使用偏左裁切。 |
| `核验/automated_acceptance_tests.json`、`核验/material_manifest.csv` | `./evidence/automated-acceptance-tests.json`、`./evidence/material-manifest.csv` | T01-T07 通过记录及来源素材哈希。 |

## 本项目已经完成的接入成果

| 能力 | 本包相对入口 | 已实现的呈现 |
| --- | --- | --- |
| 互动产品演示 | `./index.html` | 素材选择、A/B/C 版本比较、段落编辑与来源归因、确认快照、阅读端字号切换和回复流程。 |
| 受控数据桥接 | `./demo-case.js`、`./demo-case.json` | 将队友审核稿装入页面；照片和语音均采用相对路径，换电脑或换盘符不需要改配置。 |
| 来源与隐私门禁 | `./manifest.json` | 固定验证三项主来源的 SHA-256、照片物理裁切参数、衍生图哈希、音频哈希、证据副本哈希与相对路径。 |
| 可汇报长图 | `./exports/warm-letter-case-001-recommended-a.png` | 1080 px 宽的推荐 A 成果长图，含真实裁切图、完整称呼、正文、署名和固定审核披露语。 |
| 长图核验 | `./exports/warm-letter-case-001-recommended-a.manifest.json` | 验证推荐版本、正文哈希、裁切图、尺寸、像素非空和无路径或凭据泄漏。 |
| 团队交接包 | `./README.md`、`./PROJECT_INTEGRATION.md` | ZIP 使用相对路径，包含媒体、证据和长图；原图不会被打包。 |

## 复核顺序

1. 打开 `index.html`，比较 A/B/C 后推进到确认和阅读端；确认照片、原声与 T01-T07 均可见。
2. 查看 `exports/warm-letter-case-001-recommended-a.png`，用于群内或汇报时快速展示推荐成果。
3. 打开 `manifest.json`，核对素材、裁切图、证据和长图的 SHA-256。
4. 需要追溯判断时，依次查看 `evidence/` 下的输出样例、安全规则、隐私审查、验收与素材清单。

## 未完成边界

- 这是固定 CASE-001 的可交互演示，不是实时生成服务；未接入生产模型调用、账号、数据库、消息发送或外网分享。
- 包内语音和照片只适合团队授权范围内展示；原始照片已排除，公开发布前仍需确认素材授权范围。
- 真人用户测试工具、评分数据、DOCX 成果册和开发输入材料保留在队友原成果包中，未复制进本展示 ZIP。
- 新案例接入前必须重新做素材核验、隐私裁切、内容审核和 T01-T07 同类回归，不能把本案例结论直接外推。
'@
  Write-Utf8File -LiteralPath (Join-Path $stage 'PROJECT_INTEGRATION.md') -Content ($projectIntegration.TrimStart() + "`n")

  $manifest = [ordered]@{
    schemaVersion = 1
    packageKind = $packageKind
    materialId = $materialId
    sourceIntegrity = [ordered]@{
      photo = [ordered]@{ relativePath = $expectedSources.photo.relativePath.Replace('\', '/'); bytes = $photoSource.bytes; sha256 = $photoSource.sha256 }
      audio = [ordered]@{ relativePath = $expectedSources.audio.relativePath.Replace('\', '/'); bytes = $audioSource.bytes; sha256 = $audioSource.sha256 }
      draftText = [ordered]@{ relativePath = $expectedSources.draftText.relativePath.Replace('\', '/'); bytes = $draftTextSource.bytes; sha256 = $draftTextSource.sha256 }
    }
    outputs = [ordered]@{
      photo = [ordered]@{
        path = 'media/case-001-photo-crop.jpg'
        sourceRelativePath = $expectedSources.photo.relativePath.Replace('\', '/')
        mediaType = 'image/jpeg'
        bytes = (Get-Item -LiteralPath $photoOutput).Length
        sha256 = $derivedPhotoHash
        width = $crop.width
        height = $crop.height
        crop = [ordered]@{
          sourceWidth = $expectedPhotoWidth
          sourceHeight = $expectedPhotoHeight
          x = $crop.x
          y = $crop.y
          width = $crop.width
          height = $crop.height
          jpegQuality = $crop.jpegQuality
          method = 'System.Drawing physical pixel crop'
        }
      }
      audio = [ordered]@{
        path = 'media/case-001-audio.m4a'
        sourceRelativePath = $expectedSources.audio.relativePath.Replace('\', '/')
        mediaType = 'audio/mp4'
        bytes = (Get-Item -LiteralPath $audioOutput).Length
        sha256 = $copiedAudioHash
        durationSeconds = 8.895
      }
      demoCaseJson = [ordered]@{
        path = 'demo-case.json'
        sourceRelativePath = $expectedSources.draftText.relativePath.Replace('\', '/')
        sha256 = Get-LowerSha256 -LiteralPath (Join-Path $stage 'demo-case.json')
      }
      demoCaseScript = [ordered]@{
        path = 'demo-case.js'
        sha256 = Get-LowerSha256 -LiteralPath (Join-Path $stage 'demo-case.js')
      }
      demoPage = [ordered]@{
        path = 'index.html'
        sha256 = Get-LowerSha256 -LiteralPath (Join-Path $stage 'index.html')
      }
      projectIntegration = [ordered]@{
        path = 'PROJECT_INTEGRATION.md'
        sha256 = Get-LowerSha256 -LiteralPath (Join-Path $stage 'PROJECT_INTEGRATION.md')
      }
      evidence = $evidenceOutputs
    }
    longImage = $longImageOutput
    controls = [ordered]@{
      pathsAreRelative = $true
      originalPhotoIncluded = $false
      credentialsIncluded = $false
      sourceFilesModified = $false
      sourceEvidenceCopiedVerbatim = $true
      longImageIncluded = ($null -ne $longImageOutput)
      privacyBoundary = '仅保留固定裁切矩形内像素；裁切外人物信息不识别、不描述、不进入展示图'
    }
  }
  Write-Utf8File -LiteralPath (Join-Path $stage 'manifest.json') -Content (($manifest | ConvertTo-Json -Depth 12) + "`n")

  Assert-GeneratedTextSafety -Root $stage

  if ((Get-LowerSha256 -LiteralPath $photoSource.path) -ne $photoSource.sha256) {
    throw 'Source photo changed during packaging.'
  }
  if ((Get-LowerSha256 -LiteralPath $audioSource.path) -ne $audioSource.sha256) {
    throw 'Source audio changed during packaging.'
  }
  if ((Get-LowerSha256 -LiteralPath $draftTextSource.path) -ne $draftTextSource.sha256) {
    throw 'Source draft text changed during packaging.'
  }

  if (-not $SkipArchive) {
    $archiveStageExists = $true
    New-ControlledArchive -SourceDirectory $stage -ArchivePath $archiveStage
    Assert-ControlledArchive -ArchivePath $archiveStage -RequiredEntries $requiredArchiveEntries | Out-Null
  }

  if (Test-Path -LiteralPath $outputRootFull) {
    if (-not (Test-Path -LiteralPath $outputRootFull -PathType Container)) {
      throw 'OutputRoot exists but is not a directory.'
    }

    $existingManifestPath = Join-Path $outputRootFull 'manifest.json'
    if (-not (Test-Path -LiteralPath $existingManifestPath -PathType Leaf)) {
      throw 'Refusing to replace an existing directory without a recognized manifest.'
    }

    try {
      $existingManifest = Get-Content -LiteralPath $existingManifestPath -Raw -Encoding UTF8 | ConvertFrom-Json
    } catch {
      throw 'Refusing to replace an existing directory with an invalid manifest.'
    }
    if ($existingManifest.packageKind -ne $packageKind -or $existingManifest.materialId -ne $materialId) {
      throw 'Refusing to replace an existing directory owned by another package.'
    }
  }

  if (-not $SkipArchive -and (Test-Path -LiteralPath $archivePath)) {
    if (-not (Test-Path -LiteralPath $archivePath -PathType Leaf)) {
      throw 'Archive path exists but is not a file.'
    }
    # Older valid packages did not yet contain evidence/ and exports/. Verify
    # their safe ownership before atomically upgrading them to the current layout.
    Assert-ControlledArchive -ArchivePath $archivePath -RequiredEntries $minimumExistingArchiveEntries | Out-Null
  }

  if (Test-Path -LiteralPath $outputRootFull) {
    Move-Item -LiteralPath $outputRootFull -Destination $backup
    $backupExists = $true
  }
  if (-not $SkipArchive -and (Test-Path -LiteralPath $archivePath)) {
    Move-Item -LiteralPath $archivePath -Destination $archiveBackup
    $archiveBackupExists = $true
  }

  try {
    Move-Item -LiteralPath $stage -Destination $outputRootFull
    $stageExists = $false
    $newOutputInstalled = $true

    if (-not $SkipArchive) {
      Move-Item -LiteralPath $archiveStage -Destination $archivePath
      $archiveStageExists = $false
      $newArchiveInstalled = $true
    }
  } catch {
    if ($newArchiveInstalled -and (Test-Path -LiteralPath $archivePath)) {
      Remove-Item -LiteralPath $archivePath -Force
      $newArchiveInstalled = $false
    }
    if ($archiveBackupExists -and -not (Test-Path -LiteralPath $archivePath)) {
      Move-Item -LiteralPath $archiveBackup -Destination $archivePath
      $archiveBackupExists = $false
    }
    if ($newOutputInstalled -and (Test-Path -LiteralPath $outputRootFull)) {
      Remove-Item -LiteralPath $outputRootFull -Recurse -Force
      $newOutputInstalled = $false
    }
    if ($backupExists -and -not (Test-Path -LiteralPath $outputRootFull)) {
      Move-Item -LiteralPath $backup -Destination $outputRootFull
      $backupExists = $false
    }
    throw
  }

  if ($backupExists) {
    Remove-Item -LiteralPath $backup -Recurse -Force
    $backupExists = $false
  }
  if ($archiveBackupExists) {
    Remove-Item -LiteralPath $archiveBackup -Force
    $archiveBackupExists = $false
  }
} finally {
  if ($stageExists -and (Test-Path -LiteralPath $stage)) {
    Remove-Item -LiteralPath $stage -Recurse -Force
  }
  if ($archiveStageExists -and (Test-Path -LiteralPath $archiveStage)) {
    Remove-Item -LiteralPath $archiveStage -Force
  }
  if ($backupExists -and (Test-Path -LiteralPath $backup) -and -not (Test-Path -LiteralPath $outputRootFull)) {
    Move-Item -LiteralPath $backup -Destination $outputRootFull
    $backupExists = $false
  }
  if ($archiveBackupExists -and (Test-Path -LiteralPath $archiveBackup) -and -not (Test-Path -LiteralPath $archivePath)) {
    Move-Item -LiteralPath $archiveBackup -Destination $archivePath
    $archiveBackupExists = $false
  }
}

$resultManifest = Get-Content -LiteralPath (Join-Path $outputRootFull 'manifest.json') -Raw -Encoding UTF8 | ConvertFrom-Json
if ($RequireLongImage -and -not [bool]$resultManifest.controls.longImageIncluded) {
  throw 'Final handoff requested a long image, but the installed manifest does not record one.'
}
Write-Host "Created controlled demo: $outputRootFull"
Write-Host "Photo crop: x=$($crop.x), y=$($crop.y), width=$($crop.width), height=$($crop.height)"
Write-Host "Derived photo SHA-256: $($resultManifest.outputs.photo.sha256)"
if (-not $SkipArchive) {
  $archiveValidation = Assert-ControlledArchive -ArchivePath $archivePath -RequiredEntries $requiredArchiveEntries
  Write-Host "Created archive: $archivePath"
  Write-Host "Archive entries checked: $($archiveValidation.entryCount)"
  Write-Host "Archive SHA-256: $(Get-LowerSha256 -LiteralPath $archivePath)"
}
if ([bool]$resultManifest.controls.longImageIncluded) {
  Write-Host "Reviewed long image preserved: $($resultManifest.longImage.png.path)"
}
Write-Host 'Integrity, evidence-copy, relative-path, sensitive-text, long-image, and source-read-only checks: PASS'
